name: Build Smash Soda (Windows)

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Instalar ATL (Visual Studio)
        shell: pwsh
        run: |
          $vsPath = & "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe" -latest -property installationPath
          & "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vs_installer.exe" modify `
            --installPath $vsPath `
            --add Microsoft.VisualStudio.Component.VC.ATL `
            --quiet --norestart --force

      - name: Instalar vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git C:\vcpkg
          C:\vcpkg\bootstrap-vcpkg.bat
          C:\vcpkg\vcpkg integrate install

      - name: Build Release x64
        run: msbuild ParsecSoda.sln /p:Configuration=Release /p:Platform=x64 /m

      - name: Criar Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: build-${{ github.run_number }}
          name: "Build #${{ github.run_number }}"
          files: x64/Release/**
          fail_on_unmatched_files: false
