name: Build Smash Soda (Windows)

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar dependências do sistema
        run: choco install ninja

      - name: Instalar vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          .\vcpkg\bootstrap-vcpkg.bat

      - name: Configurar e gerar build com CMake
        run: |
          mkdir build
          cd build
          cmake ..\engine -DCMAKE_TOOLCHAIN_FILE=..\vcpkg\scripts\buildsystems\vcpkg.cmake -G "Ninja" -DCMAKE_BUILD_TYPE=Release

      - name: Compilar
        run: cmake --build build --config Release
